### ISSUE TITLE
UI Tests check is failing on CI

### ISSUE THREAD

**Issue by jtpio** [widgetti/ipyvolume#413]
Opening a new issue since the check is failing on the latest commit on `master`: https://github.com/widgetti/ipyvolume/commit/1c08f9fdde4219be873f7c45e02ecec2540d5876

![image](https://user-images.githubusercontent.com/591645/181188369-887c83c8-6720-4520-aa11-dd36f4091a20.png)

Opening the report shows some differences with the UI elements: 

![image](https://user-images.githubusercontent.com/591645/181188256-19be857b-3495-4903-b7e4-09a9a16bed63.png)

Not sure if this was introduced in a previous PR, but probably updating the reference snapshots should help fix it.

**Comment by jtpio** [comment]
Also the UI Tests setup could be updated to use a newer `@jupyterlab/galata`: https://github.com/jupyterlab/jupyterlab/tree/master/galata

For example:

- https://github.com/voila-dashboards/voila/tree/main/ui-tests
- https://github.com/jupyter-widgets/ipyleaflet/tree/master/ui-tests

**Comment by jtpio** [comment]
Upgrading to the newer setup would also allow for integrations like automated snapshots updates with a bot: https://github.com/jupyterlab/maintainer-tools#update-snapshots

**Comment by maartenbreddels** [comment]
Partially fixed in https://github.com/widgetti/ipyvolume/pull/424
(not yet upgraded, will keep that in mind!)
